export const userList = [
    { id: 1, name: "John Doe", email: "johndoe@gmail.com", image: "https://randomuser.me/api/portraits/men/1.jpg" },
    { id: 2, name: "Jane Smith", email: "janesmith@gmail.com", image: "https://randomuser.me/api/portraits/women/1.jpg" },
    { id: 3, name: "Michael Brown", email: "michaelbrown@example.com", image: "https://randomuser.me/api/portraits/men/2.jpg" },
    { id: 4, name: "Emily Johnson", email: "emily.johnson@company.com", image: "https://randomuser.me/api/portraits/women/2.jpg" },
    { id: 5, name: "Chris Wilson", email: "chris.wilson@xyz.com", image: "https://randomuser.me/api/portraits/men/3.jpg" },
    { id: 6, name: "Sarah Miller", email: "sarahmiller@example.com", image: "https://randomuser.me/api/portraits/women/3.jpg" },
    { id: 7, name: "David Lee", email: "davidlee@techworld.com", image: "https://randomuser.me/api/portraits/men/4.jpg" },
    { id: 8, name: "Sophia Martinez", email: "sophia.martinez@gmail.com", image: "https://randomuser.me/api/portraits/women/4.jpg" },
    { id: 9, name: "James Anderson", email: "james.anderson@domain.com", image: "https://randomuser.me/api/portraits/men/5.jpg" },
    { id: 10, name: "Olivia Taylor", email: "olivia.taylor@gmail.com", image: "https://randomuser.me/api/portraits/women/5.jpg" },
    { id: 11, name: "Daniel White", email: "danielwhite@example.com", image: "https://randomuser.me/api/portraits/men/6.jpg" },
    { id: 12, name: "Emma Harris", email: "emma.harris@xyz.com", image: "https://randomuser.me/api/portraits/women/6.jpg" },
    { id: 13, name: "Matthew Scott", email: "matthew.scott@example.com", image: "https://randomuser.me/api/portraits/men/7.jpg" },
    { id: 14, name: "Ava King", email: "ava.king@company.com", image: "https://randomuser.me/api/portraits/women/7.jpg" },
    { id: 15, name: "Ethan Lewis", email: "ethan.lewis@gmail.com", image: "https://randomuser.me/api/portraits/men/8.jpg" },
];
